#!/bin/bash

print_usage() {
  printf '\nUsage: %s: [OPTION] script\n' $0
  echo "A script must be provided."
  echo "OPTIONS:"
  echo "	-e 	Filename for the stderr redirection (default: ./err.log)"
  echo "	-o 	Filename for the stdout redirection (default: ./out.log)"
}

SCRIPT=false
ERRLOG="./err.log"
OUTLOG="./out.log"

while getopts ':e:o:' flag; do
  case "${flag}" in
    e) ERRLOG=${OPTARG} ;;
    o) OUTLOG=${OPTARG} ;;
    ?) print_usage
       exit 1 ;;
  esac
done

echo ""

if [ "$#" -lt 1 ]
then
    echo "Illegal number of parameters."
    print_usage
    exit 1
fi

shift $((OPTIND-1))

if [ "$#" -lt 1 ]
then
    echo "Missing script parameter."
    print_usage
    exit 1
fi

SCRIPT=$@

($SCRIPT | tee $OUTLOG) 3>&1 1>&2 2>&3 | tee $ERRLOG
